apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nginx
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nginx
    spec:
      containers:
      - name: nginx
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}
        env:
        - name: SECRET_NAME
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: packops-name
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        volumeMounts:
        - name: nginx-files
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-files
        configMap:
          name: {{ .Release.Name }}-configmap
      restartPolicy: Always
